# -*- coding: utf-8 -*-
"""stable-diffusionIMAGE_MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWEesUxqQ_fjlBUMXT4y49wv71LG_ivr

#**STABLE DIFFUSION-v1-5 (IMAGE MODEL)**
"""

!pip install -U diffusers

from diffusers import StableDiffusionPipeline
import torch
from IPython.display import display

pipe = StableDiffusionPipeline.from_pretrained(
    "stable-diffusion-v1-5/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")
prompt = "some village people, working on the field"
image = pipe(prompt, height=280, width=280, num_inference_steps=25).images[0]
image.save("output.png")
print(image)
display(image)

"""##**GENERATING MULTIPLE IMAGES IN ONE LOOP.**
Generating multiple images by putting the image generation code inside a loop. Here's an example that generates three images with slightly different prompts:
"""

prompts = [
    "a fantasy landscape, beautiful sunset",
    "a futuristic city at night",
    "a serene forest in autumn"
]

for i, prompt in enumerate(prompts):
    print(f"Generating image for prompt: {prompt}")
    image = pipe(prompt, height=280, width=280, num_inference_steps=25).images[0]
    image_filename = f"output_{i+1}.png"
    image.save(image_filename)
    print(f"Image saved as {image_filename}")
    display(image)